# Generated by Django 3.1.5 on 2021-01-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210107_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rate_per_hour',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration_in_hours', models.FloatField()),
                ('report', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.profile')),
                ('student', models.ManyToManyField(to='lessons.Student')),
            ],
        ),
    ]
