# Generated by Django 3.1.4 on 2021-01-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_invoice_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date']},
        ),
    ]
