# Generated by Django 3.1.4 on 2021-01-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='studentss',
            field=models.ManyToManyField(to='lessons.Student'),
        ),
    ]
