# Generated by Django 3.1.4 on 2021-01-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_group_studentss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='studentss',
            new_name='students',
        ),
    ]
