# Generated by Django 3.1.4 on 2021-01-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20210111_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='lessons.Group'),
        ),
    ]
