# Generated by Django 3.1.5 on 2021-01-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_invoice_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='students',
        ),
        migrations.AddField(
            model_name='group',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.profile'),
            preserve_default=False,
        ),
    ]
